version: "3.8"

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./cats-db-data:/data/db
    networks:
      - main-network
  
  backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4200:4200
    depends_on:
      - mongodb
    networks:
      - main-network

  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - main-network

networks:
  main-network:

